version: "3.9"
services: 
  db:
    image: mongo
    ports: 
      - "27017:27017"
  back:
    build: .
    environment: 
      - API_KEY=${API_KEY}
    ports: 
      - "3000:3000"
    depends_on:
      - db
  